unsetopt auto_cd
unsetopt correct_all

alias ls="ls -G"
alias ll="ls -lah"
alias l="ll"

export PATH=$HOME/bin:$PATH
export EDITOR=vim
export CC=/usr/bin/clang
export MANPATH=/usr/share/man:$MANPATH

if [ -d $HOME/.zshrc.d ]; then
  for file in $HOME/.zshrc.d/*.zsh; do
    source $file
  done
fi
