unsetopt auto_cd
unsetopt correct_all

alias ls="ls -G"
alias ll="ls -lah"
alias l="ll"

if [ -f /etc/profile ]; then
    PATH=""
    source /etc/profile
fi

export PATH=$HOME/bin:$PATH
eval "$(/opt/homebrew/bin/brew shellenv)"
export EDITOR=vim
export CC=/usr/bin/clang
export MANPATH=/usr/share/man:$MANPATH

#echo "### about to source stuff"
if [ -d $HOME/.zshrc.d ]; then
  for file in $HOME/.zshrc.d/*.zsh; do
    #echo "### sourcing: $file"
    #time (source $file)
    source $file
  done
fi
#echo "### done sourcing stuff"

ulimit -n 4096
